### ISSUE TITLE
Search page list elements are cut short

### ISSUE THREAD

**Issue by nathandolbir** [SCCapstone/CampusConnect#232] opened 2023-04-10 02:15 UTC
Screenshot_20230409_221356_Campus Connect.jpg](https://user-images.githubusercontent.com/75330713/230811814-03769d36-0492-446f-b056-ac2079f501c3.jpg)

**Comment by NSarmadi** [comment] 2023-04-10 02:41
Duplicate of #215

**Closed by NSarmadi** 2023-04-10 02:41 UTC
Labels: duplicate
