### ISSUE TITLE
Clicking on a club has an animation, but nothing happens

### ISSUE THREAD

**Issue by TylerTBarrett** [SCCapstone/CampusConnect#217] opened 2023-04-08 19:45 UTC
On the clubs screen, when you click on one of the clubs, there is an animation that indicates it's clickable, but nothing happens

https://user-images.githubusercontent.com/77293077/230739929-4699f7af-9031-4e02-bf2a-92343def71e8.mp4

**Comment by econnerty** [comment] 2023-04-09 14:48
duplicate of #202

**Closed by econnerty** 2023-04-09 14:48 UTC
Labels: duplicate
